version: 0.2
    phases:
    install:
        runtime-versions:
            java: openjdk8
    build:
      commands:
        - echo Running tests 
    reports:
      opa-unittest-report: #test file information
      files:
        - 'opa-unit-test-coverage-report.json'
      file-format: 'SIMPLECOV'
